export const TAG_SELECTED = "TAG_SELECTED";
export const SHOW_LOGIN_SCREEN = "SHOW_LOGIN_SCREEN";
export const SHOW_MESSAGES_SCREEN = "SHOW_MESSAGES_SCREEN";
export const NEW_MESSAGE_ADDED = "NEW_MESSAGE_ADDED";
export const NEW_CONTACT_ADDED = "NEW_CONTACT_ADDED";
export const SHOW_CONTACT_SCREEN = "SHOW_CONTACT_SCREEN";
export const CONTACT_SELECTED = "CONTACT_SELECTED";
